### ISSUE TITLE
Cannot find Motilal Oswal Mid Cap fund

### ISSUE THREAD

**Issue by lakshits11** [asrajavel/mf-analysis#18]
I think the names are not updated in mf list. I tried to search for Motilal Oswal MidCap fund but vould not find it.

![Screenshot_2024_0619_094746](https://github.com/asrajavel/mf-analysis/assets/54276661/7df5407e-2cf9-496d-ae05-76306d1ba89e)

Maybe try to add mutual fund codes also to webiste? Or try to fix the names?
Thank You.

**Comment by asrajavel** [comment]
you will need to type full words: try this "Motilal Oswal Midcap" it works

**Comment by lakshits11** [comment]
Also why these duplicate entries: (quant midcap)

![image](https://github.com/asrajavel/mf-analysis/assets/54276661/32800ee9-1968-4df4-b48c-4455f7838e58)
