### ISSUE TITLE
Motilal oswal midcap 150 index fund is missing

### ISSUE THREAD

**Issue by sanketgarade** [asrajavel/mf-analysis#5]
Can you please add this?

![image](https://github.com/asrajavel/mf-analysis/assets/74632379/dc1b16b7-9527-4db3-ab4b-3d2c9c098294)

**Comment by asrajavel** [comment]
somehow the fund name does not have 'growth' in it,
so remove the tick mark below the text box and search again, you can find it.
Thanks.
